+include managed.css.slang

.editorlist .listitem
	border-bottom	0 !important
	border-left		1px dashed

.scene
	background		@primaryl
	margin			6px 0
.scene input.title
	border-bottom	0
	padding			0 12px
.scene button
	padding			16px

.action
	margin			6px 10%
	padding			6px

.dialog
	margin			6px 20%
	padding			6px

.dialog input, .dialog textarea
	border-bottom	0

.dialog .name, .dialog .parenthetical
	width			80%
	margin			6px auto
	text-align		center

